export default [
  {
    name: "Vercel",
    slug: "vercel/project",
    category: "hosting",
    description: "Frontend cloud platform",
    longDescription: "Deploy frontend apps to the edge with automatic CI/CD, edge functions, and global CDN distribution. Seamless integration with Next.js and all major frameworks.",
    url: "https://vercel.com",
    logoTag: "logo-vercel",
  },
  {
    name: "Railway",
    slug: "railway/hosting",
    category: "hosting",
    description: "Infrastructure for devs",
    longDescription: "Railway is the all-in-one intelligent cloud provider. Deploy servers, databases, and cron jobs with zero ops overhead.",
    url: "https://railway.app",
    logoTag: "logo-railway",
  },
  {
    name: "Supabase",
    slug: "supabase/supabase:free",
    category: "database",
    description: "Open source Firebase alternative",
    longDescription: "Supabase is the easy-to-use, open-source managed Postgres with integrated backend services — Database, Auth, Storage, Edge Functions, Realtime, and Vector search.",
    url: "https://supabase.com",
    logoTag: "logo-supabase",
  },
  {
    name: "Neon",
    slug: "neon/postgres",
    category: "database",
    description: "Serverless Postgres",
    longDescription: "Neon is a fully-managed Postgres database platform built on a distributed architecture that separates storage and compute, delivering instant provisioning, autoscaling, and branching.",
    url: "https://neon.tech",
    logoTag: "logo-neon",
  },
  {
    name: "Turso",
    slug: "turso/database",
    category: "database",
    description: "SQLite for the agentic era",
    longDescription: "Turso Cloud gives AI agents the fast, durable, and isolated state they need to run reliably at scale. Each agent gets its own lightweight, replicated SQLite-compatible database with fast reads, built-in vector search, and automatic sync.",
    url: "https://turso.tech",
    logoTag: "logo-turso",
  },
  {
    name: "PlanetScale",
    slug: "planetscale/postgresql",
    category: "database",
    description: "Serverless MySQL platform",
    longDescription: "PlanetScale is a fully managed database platform for Postgres and Vitess/MySQL, delivering NVMe-backed performance, massive scale through horizontal sharding, and enterprise-grade reliability.",
    url: "https://planetscale.com",
    logoTag: "logo-planetscale",
  },
  {
    name: "Chroma",
    slug: "chroma/database",
    category: "vector-db",
    description: "AI-native vector database",
    longDescription: "Fast, serverless, and scalable search engine supporting vector, full-text, regex, and metadata search. Built on object storage and trusted by millions of developers. Open-source Apache 2.0.",
    url: "https://trychroma.com",
    logoTag: "logo-chroma",
  },
  {
    name: "Clerk",
    slug: "clerk/auth",
    category: "auth",
    description: "Auth & user management",
    longDescription: "Drop-in authentication with social login, magic links, MFA, and full user management UI. Works out of the box with zero configuration.",
    url: "https://clerk.dev",
    logoTag: "logo-clerk",
  },
  {
    name: "PostHog",
    slug: "posthog/analytics",
    category: "analytics",
    description: "Product analytics",
    longDescription: "PostHog is the single platform for software teams — with analytics, session replay, feature flags, A/B testing, data warehouse, CDP, and more all in one AI-powered platform.",
    url: "https://posthog.com",
    logoTag: "logo-posthog",
  },
  {
    name: "Runloop",
    slug: "runloop/sandbox",
    category: "sandbox",
    description: "AI dev infrastructure",
    longDescription: "Runloop provides secure execution infrastructure for AI agents. Run agent workloads inside isolated micro-VM sandboxes, allowing agents to safely execute code, use tools, and access external systems.",
    url: "https://runloop.ai",
    logoTag: "logo-runloop",
  },
  {
    name: "Cloudflare",
    slug: "cloudflare/worker",
    category: "hosting",
    description: "Edge platform for apps",
    longDescription: "Cloudflare is the edge platform for running, securing, and accelerating applications without managing infrastructure. Deploy code and services to a global network that handles routing, protection, and performance close to users by default.",
    url: "https://cloudflare.com",
    logoTag: "logo-cloudflare",
  },
  {
    name: "Fly.io",
    slug: "flyio/app",
    category: "hosting",
    description: "Global app deployment platform",
    longDescription: "Deploy full-stack apps and databases globally on fast hardware with low-latency networking. Run containers close to your users with built-in Postgres, Redis, and private networking.",
    url: "https://fly.io",
    logoTag: "logo-flyio",
  },
  {
    name: "Openrouter",
    slug: "openrouter/api",
    category: "ai",
    description: "Unified AI model API",
    longDescription: "Openrouter provides a single API to access hundreds of AI models from OpenAI, Anthropic, Google, Meta, and more. Route to the best model for cost, speed, or capability automatically.",
    url: "https://openrouter.ai",
    logoTag: "logo-openrouter",
  },
  {
    name: "Hugging Face",
    slug: "huggingface/platform",
    category: "ai",
    description: "Open-source AI platform",
    longDescription: "Hugging Face is the ML platform for hosting, training, and deploying models and datasets. Access thousands of open-source models and run inference with a simple API.",
    url: "https://huggingface.co",
    logoTag: "logo-huggingface",
  },
  {
    name: "Inngest",
    slug: "inngest/app",
    category: "ai",
    description: "AI workflow orchestration",
    longDescription: "Inngest is the event-driven platform for background jobs, scheduled tasks, and long-running AI workflows. Built-in retries, step functions, fan-out, and full observability without managing queues.",
    url: "https://inngest.com",
    logoTag: "logo-inngest",
  },
  {
    name: "Firecrawl",
    slug: "firecrawl/api",
    category: "search",
    description: "Web scraping & crawling API",
    longDescription: "Firecrawl turns any website into clean, structured data for AI applications. Crawl, scrape, and extract content at scale with built-in JS rendering, markdown output, and LLM-ready formatting.",
    url: "https://firecrawl.dev",
    logoTag: "logo-firecrawl",
  },
  {
    name: "Amplitude",
    slug: "amplitude/analytics",
    category: "analytics",
    description: "Digital analytics platform",
    longDescription: "Amplitude is the digital analytics platform for understanding user behavior, building conversion funnels, measuring retention, and running A/B experiments to drive product growth.",
    url: "https://amplitude.com",
    logoTag: "logo-amplitude",
  },
  {
    name: "Mixpanel",
    slug: "mixpanel/analytics",
    category: "analytics",
    description: "Event-based product analytics",
    longDescription: "Mixpanel tracks user events and interactions to help teams understand behavior, build funnels, measure retention, and make data-driven decisions without a data warehouse.",
    url: "https://mixpanel.com",
    logoTag: "logo-mixpanel",
  },
];
