export default [
  {
    name: "Vercel",
    slug: "vercel/project",
    category: "hosting",
    description: "Frontend cloud platform",
    longDescription: "Deploy frontend apps to the edge with automatic CI/CD, edge functions, and global CDN distribution. Seamless integration with Next.js and all major frameworks.",
    url: "https://vercel.com",
    logoTag: "logo-vercel",
  },
  {
    name: "Railway",
    slug: "railway/hosting",
    category: "hosting",
    description: "Infrastructure for devs",
    longDescription: "Railway is the all-in-one intelligent cloud provider. Deploy servers, databases, and cron jobs with zero ops overhead.",
    url: "https://railway.app",
    logoTag: "logo-railway",
  },
  {
    name: "Supabase",
    slug: "supabase/supabase:free",
    category: "database",
    description: "Open source Firebase alternative",
    longDescription: "Supabase is the easy-to-use, open-source managed Postgres with integrated backend services — Database, Auth, Storage, Edge Functions, Realtime, and Vector search.",
    url: "https://supabase.com",
    logoTag: "logo-supabase",
  },
  {
    name: "Neon",
    slug: "neon/postgres",
    category: "database",
    description: "Serverless Postgres",
    longDescription: "Neon is a fully-managed Postgres database platform built on a distributed architecture that separates storage and compute, delivering instant provisioning, autoscaling, and branching.",
    url: "https://neon.tech",
    logoTag: "logo-neon",
  },
  {
    name: "Turso",
    slug: "turso/database",
    category: "database",
    description: "SQLite for the agentic era",
    longDescription: "Turso Cloud gives AI agents the fast, durable, and isolated state they need to run reliably at scale. Each agent gets its own lightweight, replicated SQLite-compatible database with fast reads, built-in vector search, and automatic sync.",
    url: "https://turso.tech",
    logoTag: "logo-turso",
  },
  {
    name: "PlanetScale",
    slug: "planetscale/postgresql",
    category: "database",
    description: "Serverless MySQL platform",
    longDescription: "PlanetScale is a fully managed database platform for Postgres and Vitess/MySQL, delivering NVMe-backed performance, massive scale through horizontal sharding, and enterprise-grade reliability.",
    url: "https://planetscale.com",
    logoTag: "logo-planetscale",
  },
  {
    name: "Chroma",
    slug: "chroma/database",
    category: "vector-db",
    description: "AI-native vector database",
    longDescription: "Fast, serverless, and scalable search engine supporting vector, full-text, regex, and metadata search. Built on object storage and trusted by millions of developers. Open-source Apache 2.0.",
    url: "https://trychroma.com",
    logoTag: "logo-chroma",
  },
  {
    name: "Clerk",
    slug: "clerk/auth",
    category: "auth",
    description: "Auth & user management",
    longDescription: "Drop-in authentication with social login, magic links, MFA, and full user management UI. Works out of the box with zero configuration.",
    url: "https://clerk.dev",
    logoTag: "logo-clerk",
  },
  {
    name: "PostHog",
    slug: "posthog/analytics",
    category: "analytics",
    description: "Product analytics",
    longDescription: "PostHog is the single platform for software teams — with analytics, session replay, feature flags, A/B testing, data warehouse, CDP, and more all in one AI-powered platform.",
    url: "https://posthog.com",
    logoTag: "logo-posthog",
  },
  {
    name: "Runloop",
    slug: "runloop/sandbox",
    category: "sandbox",
    description: "AI dev infrastructure",
    longDescription: "Runloop provides secure execution infrastructure for AI agents. Run agent workloads inside isolated micro-VM sandboxes, allowing agents to safely execute code, use tools, and access external systems.",
    url: "https://runloop.ai",
    logoTag: "logo-runloop",
  },
];
